### ISSUE TITLE
Running hanami-api with iodine

### ISSUE THREAD

**Issue by waghanza** [hanami/api#24]
Hi @jodosha,

I'm trying to test https://github.com/boazsegev/iodine and https://github.com/socketry/falcon working as `puma` replacement for `hanami-api`
@see https://the-benchmarker.semaphoreci.com/workflows/ce7d732e-e28b-44f5-ba19-5843cb32fe07?pipeline_id=9051f815-5861-4597-be99-2ba582bf6e2e

The main advantage is either pub/sub or http 2 support.

`iodine` is failing. Have you tested this rack alternative ? Is it accurate to even consider it ?

Regards,

**Comment by adam12** [comment]
> `iodine` is failing. Have you tested this rack alternative ? Is it accurate to even consider it ?

I use Iodine in 3 projects and it works well; I mainly use it for native web socket handling. None of these projects are `hanami-api` tho.

That said, this looks like a bug in Iodine and not `hanami-api`. I can recreate the same error with a plain rackup file with same response.

```ruby
run ->(*) { [200, {}, ['']] }
```

**Comment by waghanza** [comment]
Never said their is any `bug` @adam12 😛

**Comment by adam12** [comment]
> Never said their is any `bug`

My apologies.

**Comment by waghanza** [comment]
No worries, I'll feel a bug on `iodine` then

**Comment by jodosha** [comment]
@waghanza I've tried with Falcon in the past, not production, just to run a basic local bench with it to see if it was running properly and it was.
