### ISSUE TITLE
Shared Logic for block contexts

### ISSUE THREAD

**Issue by anuj1102** [hanami/api#25]
I'm really enjoying hanami/api so far.  Is there a way to have shared logic between block contexts? I know I can write my own rack endpoint but I don't want to lose the block context apis, and my shared logic is pretty small at the moment. If not, is there a recommended approach?

Ex:

```
def my_shared_logic
   halt 401 unless authorized?
end

get "/" do
  my_shared_logic
  "Hello, world"
end

get "/" do
   my_shared_logic
  "Hello, world"
end
```

**Comment by jodosha** [comment]
@anuj1102 Could you please try #26 and tell me if that works for you? Thanks 🙂

**Comment by anuj1102** [comment]
Just tested this out, it's exactly what I needed!! Thank you for the quick response.
