### ISSUE TITLE
Rack middleware is not called when using scope with interpolation

### ISSUE THREAD

**Issue by ahx** [hanami/api#29]
## Scenario
There seems to be a problem when adding a middleware inside  a `scope` block with interpolation.
Here is an example:

```ruby
scope 'i' do
  scope ':tenant_id' do
    use LogTenantIdMiddleware

    get 'foo' do
      "Hello, world #{params[:tenant_id]}"
     end
  end
end
```

## Problem

`GET "/i/42/foo"`
- `LogTenantIdMiddleware` is **not** called
- Responds with status 200, "Hello, world 42"

`GET "/i/:tenant_id/foo"`
- `LogTenantIdMiddleware` is called
- Responds with status 200, "Hello, world :tenant_id"

## Example
Here is a [gist with a demo app](https://gist.github.com/ahx/bf92c2b6843473527e192c4bd73597c8) to illustrate the issue.

**Comment by wafcio** [comment]
I have found the source of this bug, I can try to fix it

**Comment by wafcio** [comment]
founded fix in hanami-router, I will prepare PR and past link to PR here
