### ISSUE TITLE
Usage with Rails

### ISSUE THREAD

**Issue by seanfcarroll** [hanami/api#3]
Is it possible to use this on a Rails project?

**Comment by cllns** [comment]
Definitely! `Hanami::API` is Rack-compliant and so is Rails (as are most Ruby web frameworks these days). You can map paths to different Rack apps in `config.ru`.

I just did this in a Rails application:

```
require_relative 'config/environment'

class HanamiApp < Hanami::API
  get "/" do
    "Hello, world"
  end
end

map '/rails' do
  run Rails.application
end

map '/hanami' do
  run HanamiApp.new
end
```

You can also have either one mounted at `/` and another mounted at a path and it'll just work. :)

I'd recommend splitting them off at separate paths like that if possible, but if you could also look into using [`Rack::Cascade`](https://www.rubydoc.info/gems/rack/Rack/Cascade) if you want one to mount them on the same path and 'cascade' the request down when it's not matched.

**Comment by jodosha** [comment]
@seanfcarroll If you're looking to do the opposite: mount Hanami::API into a Rails app you can just follow this article: https://guides.rubyonrails.org/routing.html#routing-to-rack-applications

```ruby
mount MyApp, at: "/my_app"
```
