### ISSUE TITLE
Release hanami-api v0.3.0?

### ISSUE THREAD

**Issue by ahx** [hanami/api#38]
I was trying out the [helpers](https://github.com/hanami/api#helpers) method until I found out that the code ([PR](https://github.com/hanami/api/pull/26)) is not released on rubygems, yet. The current [version available on rubygems](https://rubygems.org/gems/hanami-api) is version 0.2.0 and was released January 2021.

Are you planning to make a new  release that includes the `helpers` method?

**Comment by cllns** [comment]
Ah, sorry about that. Yes we'll release a new version with `helpers`. I'm not sure when though; it's not something I can do.

I updated the title to be more clear & actionable, hope you don't mind :)

In the meantime, I guess you already know this but to help others, but you can add
```ruby
gem "hanami-api", github: "hanami/api"
```
to your Gemfile then run `bundle install` to use the latest version from GitHub in your project.

**Comment by jodosha** [comment]
@ahx I'm planning it for the next week (Nov 29, 2022).
