### ISSUE TITLE
Minimal working project with Hanami API

### ISSUE THREAD

**Issue by Victorcorcos** [hanami/api#41]
Hello all,

As far as I concern, the Hanami API gem is not a full framework, but a gem that will be attached in a previously created framework, like _rails_ or _hanami_ base framework for example, is this correct?

I'm asking this question because, as mentioned in the REAME of the Hanami API [repository](https://github.com/hanami/api), we need to have a base folder structure with a `Gemfile` located inside of it to put the `gem "hanami-api"` then run `bundle install` there.

Therefore...
1. What are the steps that should be done before installing Hanami API in the project?
2. What will be the base folder structure? How to setup it?
3. What we need to have previously in order to attach the Hanami API gem?

Could you provide a light-weight example using the `hanami` base structure?

Is the Hanami API gem also designed to be used after running this command?

```rb
hanami new bookshelf
# Source: https://hanamirb.org/
```

Thanks!

**Comment by jodosha** [comment]
@Victorcorcos You closed this issue because you figured out? Do you still need help?
