### ISSUE TITLE
rack-test gem is deprecated and returning an error → undefined local variable or method `app'

### ISSUE THREAD

**Issue by Victorcorcos** [hanami/api#42]
# Description ✍️ 

After following the [testing instructions provided on the README file](https://github.com/hanami/api#testing), the following error is happening.

```rb
     NameError:
       undefined local variable or method `app' for #<RSpec::ExampleGroups::Anonymous::WhenConnecting "should successfully connect" (./spec/connection_spec.rb:9)>
```

The above error is happening when we apply the `include Rack::Test::Methods` in our test suite and execute the tests
(I tried the `rspec` and the `test-unit` test gems, both faces the same issue related to the `rack-server` gem)

As we can see here:
1. https://stackoverflow.com/a/21605767/7644846
2. https://www.appsloveworld.com/ruby/100/99/nameerror-undefined-local-variable-or-method-app-for-rails-5-1-6-upgraded

This error is related to the `'rack-test'` gem being deprecated, specifically the included code from the `include Rack::Test::Methods`.

What advice you can do now to **test the Rack Server**?

Thanks

# Scenario 🔍 

* `Gemfile`
```rb
source 'https://rubygems.org'

gem 'hanami-api'
gem 'puma' # or 'webrick', or 'thin', 'falcon'

group :test, :development do
  # Adds step-by-step debugging and stack navigation capabilities to pry using byebug.
  gem 'pry-byebug'
  gem 'rspec'
end

group :test do
  gem 'rack-test'
end
```

* `config.ru`
```rb
# frozen_string_literal: true
# bundle exec rackup

require 'bundler/setup'
require 'hanami/api'
require 'pry'

class App < Hanami::API
  get '/connect' do
    halt(403, 'Please provide the email to connect') unless params.key? :email
    # params[:email]
    'www.server-url.com.us'
  end
end

run App.new
```

* `spec/connection_spec.rb`
```rb
require 'rack/test'
require 'json'
require 'pry'

RSpec.describe do
  describe 'when connecting' do
    include Rack::Test::Methods # bring methods like #get, #post, #last_response

    it 'should successfully connect' do
      get '/connect'
      
      last_response.status.should == 200
    end
  end
end
```

The error happens after executing

```rb
rspec PATH/spec/connection_spec.rb
```

**Comment by Victorcorcos** [comment]
I just figured out the answer myself, so I'll add here the solution:

`rack-test` will test the app returned by the `app` method, so it will be expecting you to have defined `app`.

Here on the `hanami-api` gem, we should test the Rack App created from the `config.ru` file:

```rb
OUTER_APP = Rack::Builder.parse_file("config.ru").first

class TestApp < Test::Unit::TestCase
  include Rack::Test::Methods

  def app
    OUTER_APP
  end

  def test_root
    get "/"
    assert last_response.ok?
  end
end
```

**Comment by jodosha** [comment]
@Victorcorcos 

```ruby
app = App.new
```

Hanami philosophy is to use objects everywhere.
